export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DATA_LOADED = 'DATA_LOADED';

// Auth Actions
export const ADD_LOGGED_USER = 'ADD_LOGGED_USER';

// Search Actions
export const ADD_SEARCH_TAG = 'ADD_SEARCH_TAG';
export const REMOVE_SEARCH_TAG = 'REMOVE_SEARCH_TAG';
export const UPDATE_TAGS_INPUT_ERROR = 'UPDATE_TAGS_INPUT_ERROR';
export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';
export const UPDATE_LOCATION_INPUT_ERROR = 'UPDATE_LOCATION_INPUT_ERROR';
