// Root Actions
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DATA_LOADED = 'DATA_LOADED';
export const UPDATE_LOADING = 'UPDATE_LOADING';

// Auth Actions
export const ADD_LOGGED_USER = 'ADD_LOGGED_USER';

export const UPDATE_LOGGED_FIELD = 'UPDATE_LOGGED_FIELD';
export const UPDATE_LOGGED_FIELD_ERROR = 'UPDATE_LOGGED_FIELD_ERROR';
export const UPDATE_LOGGED_OBJ_FIELD = 'UPDATE_LOGGED_OBJ_FIELD';
export const UPDATE_LOGGED_OBJ_FIELD_ERROR = 'UPDATE_LOGGED_OBJ-FIELD_ERROR';
export const ADD_LOGGED_OBJ = 'ADD_LOGGED_OBJ';

export const SET_UPDATE_FORM_SUBMITTED = 'SET_UPDATE_FORM_SUBMITTED';

// Search Actions
// Tags Input
export const UPDATE_TAGS_INPUT = 'UPDATE_TAGS_INPUT';
export const ADD_SEARCH_TAG = 'ADD_SEARCH_TAG';
export const REMOVE_SEARCH_TAG = 'REMOVE_SEARCH_TAG';
export const UPDATE_TAGS_INPUT_ERROR = 'UPDATE_TAGS_INPUT_ERROR';
export const UPDATE_TAGS_INPUT_SUGGESTIONS = 'UPDATE_TAGS_INPUT_SUGGESTIONS';
// Location Input
export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';
export const UPDATE_LOCATION_INPUT_ERROR = 'UPDATE_LOCATION_INPUT_ERROR';
export const UPDATE_LOCATION_INPUT_SUGGESTIONS =
	'UPDATE_LOCATION_INPUT_SUGGESTIONS';
// Search results
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';

// Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// Header Actions
export const UPDATE_HEADER_VIEW = 'UPDATE_HEADER_VIEW';
